module.exports = [
  require('./employees'),
  require('./ps-team-assignments'),
  require('./team-utilization-inputs'),
  require('./revenue-rates'),
  require('./committed-targets'),
  require('./presale-products'),
  require('./projects'),
  require('./assignments'),
  require('./timesheets'),
  require('./dashboard-core'),
  require('./dashboard-new-logo'),
  require('./dashboard-revenue'),
  require('./dashboard-ps-type'),
  require('./misc'),
];
